### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by fitzwalker** [UTS-eResearch/pbsweb#13]
Hi Folks
Install on openhpc 3.9 with pbs 19 nodes and jobsworks on ok, there is a error queue all the test in the folder tests show it working

Internal Server Error

Exception:

AttributeError("'NoneType' object has no attribute 'split'",)

Traceback:

Traceback (most recent call last):
  File "/var/www/wsgi/pbsweb/lib/python3.6/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/var/www/wsgi/pbsweb/lib/python3.6/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/var/www/wsgi/pbsweb/lib/python3.6/site-packages/bottle.py", line 3650, in wrapper
    result = func(*args, **kwargs)
  File "./pbsweb.py", line 156, in queues_page
    queues = queue_attributes_reformat(queues)
  File "/var/www/wsgi/pbsutils.py", line 389, in queue_attributes_reformat
    max_run = int(queue['max_run'].split('=')[1].replace(']',''))
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by speleolinux** [comment]
Hi, just noticed the issue you raised. There can be quite a few things that can go wrong to cause this. It could be that you dont have a max run setting for this queue so the split is trying to split on an empty string. Of course you should not need to have max run set - I should handle that in my code. 

This week I'm currently working on getting this all working with Python 3.8 and a new release will hopefully be done this month. I'll have a look at this issue during that. Thanks for raising it here.

**Comment by speleolinux** [comment]
Now fixed. Changed pbsutils.py to check if max_runs was not set for a queue.
